name: Check
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run cov

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          directory: ./coverage/

      - name: Build
        run: npm run build
